{"name":"test01","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"did not expect to find [success!] but found [null]","trace":"java.lang.AssertionError: did not expect to find [success!] but found [null]\r\n\tat org.testng.Assert.fail(Assert.java:97)\r\n\tat org.testng.Assert.failNotEquals(Assert.java:969)\r\n\tat org.testng.Assert.assertEqualsImpl(Assert.java:131)\r\n\tat org.testng.Assert.assertEquals(Assert.java:118)\r\n\tat org.testng.Assert.assertEquals(Assert.java:563)\r\n\tat com.lrc.common.BaseTest.assertResponse(BaseTest.java:113)\r\n\tat com.lrc.testcases.Test02.test01(Test02.java:36)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.lang.reflect.Method.invoke(Method.java:498)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)\r\n\tat org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)\r\n\tat org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)\r\n\tat org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)\r\n\tat org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)\r\n\tat org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)\r\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)\r\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)\r\n\tat java.util.ArrayList.forEach(ArrayList.java:1259)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:770)\r\n\tat org.testng.TestRunner.run(TestRunner.java:591)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:402)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:304)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1102)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1032)\r\n\tat org.testng.TestNG.run(TestNG.java:1000)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)\r\n"},"stage":"finished","steps":[],"attachments":[{"name":"接口请求响应日志","source":"af111d3c-a68e-4ac4-828a-5b35a57a1be9-attachment"}],"parameters":[{"name":"arg0","value":"CaseInfo{caseId=3, interfaceName='新闻列表', title='传key和page,提取author_name', requestHeader='{}', method='post', url='/test/index?key=${key}&page=1', inputParams='{\"key\":\"\"}', expected='{\n\"reason\": \"success!\",\n\"error_code\": 0,\n\"result.page\":\"1\"\n}', dbAssert='null', extractExper='{\"author_name\":\"result.data[1].author_name\"}'}"}],"start":1680790997550,"stop":1680790999013,"uuid":"1962d544-c373-4e1a-bee8-dc2cb7dbf345","historyId":"9a6997cce002b67b55a9446c6de16391","fullName":"com.lrc.testcases.Test02.test01","labels":[{"name":"package","value":"com.lrc.testcases.Test02"},{"name":"testClass","value":"com.lrc.testcases.Test02"},{"name":"testMethod","value":"test01"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"api_auto_test_02"},{"name":"subSuite","value":"com.lrc.testcases.Test02"},{"name":"host","value":"MSI"},{"name":"thread","value":"5756@MSI.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[]}